// packages/browseros-svelte/src/BrowserOS.svelte
<script lang="ts">
  import { setContext, onDestroy } from 'svelte'
  import { type AppManifest, appManager } from '@browseros/core'
  import { BrowserOSStore } from './browser-os-store.svelte.js'
  import Desktop from './Desktop.svelte'
  import Taskbar from './Taskbar.svelte'
  import AppWindow from './AppWindow.svelte'
  import AppLoader from './AppLoader.svelte'

  let { apps, className = '', wallpaper }: { apps: AppManifest[]; className?: string; wallpaper?: string } = $props()

  // 스토어 생성 및 컨텍스트에 등록
  const store = new BrowserOSStore()
  $effect(() => {
    store.wallpaper = wallpaper
  })
  setContext('browseros', store)

  // 앱 등록
  $effect(() => {
    apps.forEach((app) => {
      appManager.registerApp(app)
    })

    return () => {
      apps.forEach((app) => {
        appManager.unregisterApp(app.id)
      })
    }
  })

  onDestroy(() => {
    store.destroy()
  })
</script>

<div class="flex flex-col h-screen bg-gradient-to-br from-blue-100 to-purple-100 overflow-hidden {className}">
  <div class="flex-1 relative">
    <Desktop />
    <!-- Window Manager -->
    {#each store.apps as app (app.id)}
      {#if store.appStates[app.id]?.isOpen}
        <AppWindow appId={app.id}>
          <AppLoader {app} />
        </AppWindow>
      {/if}
    {/each}
  </div>
  <Taskbar />
</div>

// packages/browseros-react/src/browser-os.tsx
"use client"

import { useEffect } from "react"
import { BrowserOSProvider } from "./context"
import { Desktop } from "./desktop"
import { Taskbar } from "./taskbar"
import { AppWindow } from "./app-window"
import { AppLoader } from "./app-loader"
import { useBrowserOS } from "./context"
import { type AppManifest, appManager } from "@browseros/core"

interface BrowserOSProps {
  apps: AppManifest[]
  className?: string
  wallpaper?: string
}

export function BrowserOS({ apps, className = "", wallpaper }: BrowserOSProps) {
  // 앱 등록
  useEffect(() => {
    apps.forEach((app) => {
      appManager.registerApp(app)
    })

    // 컴포넌트 언마운트 시 앱 등록 해제
    return () => {
      apps.forEach((app) => {
        appManager.unregisterApp(app.id)
      })
    }
  }, [apps])

  return (
    <BrowserOSProvider wallpaper={wallpaper}>
      <div className={`flex flex-col h-screen bg-gradient-to-br from-blue-100 to-purple-100 overflow-hidden ${className}`}>
        <div className="flex-1 relative">
          <Desktop />
          <WindowManager />
        </div>
        <Taskbar />
      </div>
    </BrowserOSProvider>
  )
}

// 창 관리자 컴포넌트
function WindowManager() {
  const { apps, appStates } = useBrowserOS()

  return (
    <>
      {apps.map((app) => {
        const state = appStates[app.id]
        if (!state || !state.isOpen) return null

        return (
          <AppWindow key={app.id} appId={app.id}>
            <AppLoader app={app} />
          </AppWindow>
        )
      })}
    </>
  )
}
